export interface Car {
    _id?: string,
    title: string,
    make: string,
    model: string,
    year: number,
    bodyStyle: string,
    description: string,
    engine: string,
    transmission: string,
    power: number,
    color: string,
    mileage: number,
    price: number,
    location: string,
    comfort: {},
    safety: {},
    others: {},
    images: string[],
    views?: string[],
    subscribers?: string[],
    comments?: string[],
    owner?: string,
    createdAt?: string,
    updatedAt?: string,
    isDeleted?: boolean,
}