export interface User {
    email: string,
    firstName: string,
    lastName: string,
    phone: string,
    _id?: string,
    password?: string,
    favorites?: string[],
    cars?: string[],
    comments?: string[],
    replies?: string[],
    isAdmin?: boolean,
    createdAt?: string,
    updatedAt?: string,
}